### ISSUE TITLE
Doesn't work in PyCharm Community 2024.1

### ISSUE THREAD

**Issue by Lampe2020** [l0drex/Intellij-KDE-Breeze-Theme#138]
### Describe the bug

When I upgraded PyCharm from 2023.* to 2024.1 and started it again it gave me a warning that this plugin is incompatible. 

### Affected theme
- [x] Dark theme
- [x] Light theme

### Affected part of the UI

The whole thing didn't work at all. 

### Expected appearance

I expected it to continue working as PyCharm didn't change noticeably between those versions. 

### Screenshots

![Screenshot_20240409_120600.png, showing the error message](https://github.com/l0drex/Intellij-KDE-Breeze-Theme/assets/140405981/9f42e070-cc27-48e6-9fd5-225ebc471402)

### Desktop

 - _Plugin Version:_ v0.3.6
 - _IDE version:_ PyCharm Community Edition 2024.1 (build number in screenshot)

### Additional notes

I think you only need to change what version numbers this plugin is nominally compatible with and see if stuff breaks, as PyCharm didn't change much at all during the update except the new major version and a new splash screen background image.

**Comment by l0drex** [comment]
A new release is on the way. Should be available once it's approved by JetBrains.

**Comment by Lampe2020** [comment]
Thanks, just got the update :)
