### ISSUE TITLE
Main editor theme remains white in dark theme, Clion 2024.1

### ISSUE THREAD

**Issue by mykhayloscherbak** [l0drex/Intellij-KDE-Breeze-Theme#143]
### Describe the bug

When Breeze dark theme is selected main editor remains white

### Affected theme
- [x ] Dark theme
- [ ] Light theme

### Affected part of the UI

C/C++ editor

### Expected appearance

Editor must be displayed in the same theme as all other UI

### Screenshots

![Снимок экрана 2024-04-20 17:33:19](https://github.com/l0drex/Intellij-KDE-Breeze-Theme/assets/58140198/7e6fee0f-1a8d-44e3-bb78-5172c8e891f4)

### Desktop

 - _Plugin Version:_ v0.3.7
 - _IDE version:_ Clion 2024.1

**Comment by l0drex** [comment]
Are you using the auto dark mode plugin by any chance? You have to manually select ui theme and editor theme in its settings

**Comment by mykhayloscherbak** [comment]
No, I'm not using auto dark. But switching editor manually to the breeze dark helps.

**Comment by l0drex** [comment]
Sorry, I kind of forgot about this…
I am pretty sure this is not an issue with this plugin, but rather some misconfiguration or a bug in the ide.
