### ISSUE TITLE
Version 0.3.3 failed to release to JetBrains

### ISSUE THREAD

**Issue by SonicGDX** [l0drex/Intellij-KDE-Breeze-Theme#73]
Just wanted to say this in case you are not aware, but the action run to submit the release failed (https://github.com/l0drex/Intellij-KDE-Breeze-Theme/actions/runs/3687752170). You may already know this, in which case close this issue. This is significant because 0.3.2 does not work on the 2022.3 release so it is important the Marketplace version gets updated

**Comment by l0drex** [comment]
Yes I know, I just hadn't time to look into this yet. Thanks anyway!

**Comment by l0drex** [comment]
I finally fixed it, the new version is now available

**Comment by l0drex** [comment]
No problem, it's always good to see that others care for this project as well 😄
